### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by pagnmickie** [abulimov/atom-gotests#5]
[Enter steps to reproduce:]

1. Open project
2. Click Packages/GO tests/Generate

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [gotests](https://github.com/abulimov/atom-gotests) package 0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/z086990/.atom/packages/gotests/lib/gotests.js:108

TypeError: Cannot read property 'getPath' of undefined
    at Object.generate (/packages/gotests/lib/gotests.js:108:26)
    at /packages/gotests/lib/gotests.js:21:95)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
  2x -0:45.6.0 gotests:generate (atom-pane.pane.active)
```

### Non-Core Packages

```
go-plus 5.8.3 
gotests 0.3.1 
platformio-ide-terminal 2.8.1 
sort-lines 0.18.0 
```

**Comment by abulimov** [comment]
Thanks for reporting, should be fixed in v0.4
